server:
  port: 8083

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
      routes:
        - id: xmall-user
          uri: lb://xmall-user
          predicates:
            - Path=/app/user/**
#          filters:
#            - name: admin-jwt

management:
  endpoints:
    web:
      exposure:
        include: "*"
