server:
  port: 8083

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
      routes:
        - id: xmall-user
          uri: lb://xmall-user
          predicates:
            - Path=/user/admin/**
#          filters:
#            - name: admin-jwt
